# Generated by Django 2.2.6 on 2019-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loan_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandata',
            name='date',
        ),
        migrations.AddField(
            model_name='loandata',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loandata',
            name='Loan_STATUS',
            field=models.CharField(default='Approved', max_length=50),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='Loan_amount',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
