# Generated by Django 2.2.6 on 2019-10-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loan_app', '0002_auto_20191030_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandata',
            name='loan_amount',
        ),
        migrations.AddField(
            model_name='loandata',
            name='Loan_amount',
            field=models.IntegerField(default=10000),
        ),
    ]
