# Generated by Django 2.2.6 on 2019-10-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loan_app', '0003_auto_20191030_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandata',
            name='date',
        ),
        migrations.AddField(
            model_name='loandata',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
