# Generated by Django 2.2.6 on 2019-10-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loan_app', '0005_auto_20191030_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandata',
            name='Status',
        ),
        migrations.AddField(
            model_name='loandata',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
