# Generated by Django 2.2.6 on 2019-10-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loan_app', '0006_auto_20191030_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandata',
            name='Loan_STATUS',
            field=models.CharField(default='Available', max_length=25),
        ),
    ]
